services:
  khadga:
    host: 0.0.0.0
    port: 7001
logging:
  level: Debug
tls:
  set: false
  ca_path: ""
  key_path: ""
# FIXME: Need to rename the service in kubernetes.  These are mimir settings
host: localhost
port: 3000
db:
  tables:
    users: users
    posts: posts
    accounts: accounts
    uploads: uploads
    comments: comments
  port: 5432
  tls: true