services:
  khadga:
    host: 0.0.0.1
    port: 7001
logging:
  level: Debug
tls:
  set: true
  ca_path: "config/khadga-test.crt"
  key_path: "config/khadga-test-pvt.key"
# FIXME: Need to rename the service in kubernetes.  These are mimir settings
# host: 127.0.0.1
# port: 3000