version: "3.7"
services:
  mongodb:
    image: "mongo:4.2-bionic"
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"
  khadga:
    build: .
    ports:
      - 7001:7001
    links:
      - mongodb
    volumes:
      - ./vision/dist:/app/dist