version: "3.7"
services:
  postgres:
    image: postgres:latest
  khadga:
    build:
      context: .
      dockerfile: ./docker/builder/Dockerfile
    ports:
      - 7001:7001
    links:
      - postgres
    volumes:
      - ./vision/dist:/apps/vision/dist