unstable_features = true
force_multiline_blocks = true
combine_control_expr = false
#comment_width = 100
indent_style = "Visual"
imports_indent = "Visual"
imports_layout = "Vertical"
#max_width = 100
merge_imports = true