[package]
name = "khadga"
version = "0.1.0"
authors = ["Sean Toner"]
edition = "2018"

[dependencies]
warp = { version = "0.2.2", features = ["tls"] }
log = "0.4.8"
env_logger = "0.7.1"
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "0.2", features = ["macros"] }
bson = "0.14.0"
config = "0.10.1"
lazy_static = "1.4.0"
futures = "0.3.4"
serde_json = "1.0.48"
pretty_env_logger = "0.4.0"
jsonwebtoken = "7.1"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.10", features = ["json"] }