[package]
name = "khadga"
version = "0.1.0"
authors = ["stoner"]
edition = "2018"

[dependencies]
tokio = "0.2.0-alpha.6"
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await", "compat"] }
warp = { path = "../../warp" }
log = "0.4.8"
env_logger = "0.7.1"
mongodb = "0.4.0"
serde = { version = "1.0.102", features = ["derive"] }