[package]
name = "khadga"
version = "0.1.0"
authors = ["stoner"]
edition = "2018"

[dependencies]
tokio = "0.2.6"
futures = { version = "0.3.1", features = ["async-await", "compat"] }
warp = { path = "../../warp" }
log = "0.4.8"
env_logger = "0.7.1"
mongodb = "0.9.0"
serde = { version = "1.0.104", features = ["derive"] }
bson = "0.14.0"