apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend: 
    serviceName: khadga-cluster-ip-service 
    servicePort: 7001

#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: ingress-service
#  annotations:
#    kubernetes.io/ingress.class: nginx
#    nginx.ingress.kubernetes.io/rewrite-target: /
#    nginx.org/server-snippet: "proxy_ssl_verify off;"
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /?(.*)
#            backend: 
#              serviceName: khadga-cluster-ip-service 
#              servicePort: 7001
  